// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szpbtdmuvdiwgvhvdgas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cGJ0ZG11dmRpd2d2aHZkZ2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjk4NDIsImV4cCI6MjA2OTcwNTg0Mn0.Oa9BQzRIdjLZ5zAowzafIray6jXrEoVF8Kqfz3GXTWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});